# Generated by Django 3.2.5 on 2021-07-08 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_lan', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='b_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='b_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.language'),
        ),
    ]
